x-templates:
  python-processor-template: &python-processor-template
    env_file:
      - .env
    environment:
      - MAX_MESSAGES=10
      - MAX_DURATION=300
    working_dir: /app
    depends_on:
      - localstack
    volumes:
      - ./processors/python/:/app/

  python-processor-build-template: &python-processor-build-template
    context: .
    dockerfile: docker/processors/python/Dockerfile

services:
  api:
    container_name: api
    build:
      dockerfile: docker/api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
      - .env.sso
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  worker-messenger-post-processing:
    container_name: worker-messenger-post-processing
    build:
      context: .
      dockerfile: docker/messenger/Dockerfile
    restart: unless-stopped
    env_file:
      - .env

  worker-messenger-awards:
    container_name: worker-messenger-awards
    build:
      context: .
      dockerfile: docker/messenger/Dockerfile
    restart: unless-stopped
    env_file:
      - .env

  worker-messenger-mailer:
    container_name: worker-messenger-mailer
    build:
      context: .
      dockerfile: docker/messenger/Dockerfile
    restart: unless-stopped
    env_file:
      - .env

  worker-scheduler-awards:
    container_name: worker-scheduler-awards
    build:
      context: .
      dockerfile: docker/messenger/Dockerfile
    restart: unless-stopped
    env_file:
      - .env

  worker-processor-sentiment:
    container_name: worker-processor-sentiment
    <<: *python-processor-template
    build:
      <<: *python-processor-build-template
      args:
        PROCESSOR_NAME: sentiment
    environment:
      - PROCESSOR_NAME=sentiment

  worker-processor-complexity:
    container_name: worker-processor-complexity
    <<: *python-processor-template
    build:
      <<: *python-processor-build-template
      args:
        PROCESSOR_NAME: complexity
    environment:
      - PROCESSOR_NAME=complexity

  worker-processor-emotions:
    container_name: worker-processor-emotions
    <<: *python-processor-template
    build:
      <<: *python-processor-build-template
      args:
        PROCESSOR_NAME: emotions
    environment:
      - PROCESSOR_NAME=emotions

volumes:
  caddy_data:
  caddy_config:
