# Development environment override
services:
  api:
    build:
      context: ./docker/api
      target: frankenphp_dev
    volumes:
      - ./api/:/app
      - ./docker/api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/api/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-coverage}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  messenger.post-processing:
    build:
      context: ./docker/messenger
      target: dev
    volumes:
      - ./api/:/app
    environment:
      QUEUE_CONSUME_LIMIT: 100
      QUEUE_MEMORY_LIMIT: 128M
      QUEUE_TIME_LIMIT: 3600
      QUEUE_FAILURE_LIMIT: 10
      SUPERVISOR_NUM_PROCS: 2
      TRANSPORT_NAME: post-processing
    tty: true
    depends_on:
      - database
      - localstack

  messenger.mailer:
    build:
      context: ./docker/messenger
      target: dev
    volumes:
      - ./api/:/app
    environment:
      QUEUE_CONSUME_LIMIT: 100
      QUEUE_MEMORY_LIMIT: 128M
      QUEUE_TIME_LIMIT: 3600
      QUEUE_FAILURE_LIMIT: 10
      SUPERVISOR_NUM_PROCS: 2
      TRANSPORT_NAME: mailer
    tty: true
    depends_on:
      - database
      - localstack

  database:
    ports:
      - "5432:5432"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    env_file:
      - .env
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    healthcheck:
      test: awslocal sqs get-queue-attributes --queue-url=$$POST_PROCESSING_SQS_QUEUE
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker/data/localstack}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/localstack/init_sns_sqs.sh:/etc/localstack/init/ready.d/init_sns_sqs.sh

  mailpit:
    image: axllent/mailpit
    container_name: "${MAILPIT_DOCKER_NAME:-mailpit}"
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
