# Production environment override
services:
  api:
    build:
      context: .
      target: prod

  worker-messenger-post-processing:
    build:
      context: .
      target: prod

  worker-messenger-awards:
    build:
      context: .
      target: prod

  worker-messenger-mailer:
    build:
      context: .
      target: prod
