# Read documentation at https://async-aws.com/integration/symfony-bundle.html
async_aws:
    config:

    # All installed clients are automatically autowired. Use this section to customize clients
    clients:

when@dev:
    async_aws:
        config:
            endpoint: '%env(AWS_ENDPOINT)%'