framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            mailer:
                dsn: '%env(MESSENGER_TRANSPORT_MAILER_DSN)%'
            new-entry-topic:
                dsn: 'sns://%env(NEW_ENTRY_PROCESSING_SNS_ARN)%'
                serializer: messenger.transport.symfony_serializer
            processor-complexity:
                dsn: '%env(MESSENGER_TRANSPORT_PROCESSOR_COMPLEXITY_DSN)%'
                serializer: App\Messenger\Serializer\NewEntryProcessorMessageSerializer
            post-processing-topic:
                dsn: 'sns://%env(POST_PROCESSING_SNS_ARN)%'
                serializer: messenger.transport.symfony_serializer
            post-processing:
                dsn: '%env(MESSENGER_TRANSPORT_POST_PROCESSING_DSN)%'
                serializer: App\Messenger\Serializer\ProcessorOutputSerializer
            award-events-topic:
                dsn: 'sns://%env(AWARD_EVENTS_SNS_ARN)%'
                serializer: messenger.transport.symfony_serializer
            awards:
                dsn: '%env(MESSENGER_TRANSPORT_AWARD_DSN)%'
                serializer: App\Messenger\Serializer\NewEntryAwardMessageSerializer
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: mailer

when@test:
   framework:
       messenger:
           transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                post-processing: test://
                awards: test://
                mailer: test://
                new-entry-topic: test://
                post-processing-topic: test://
                award-events-topic: test://
