framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            post-processing:
                dsn: '%env(MESSENGER_TRANSPORT_POST_PROCESSING_DSN)%'
                serializer: 'App\Messenger\Serializer\ProcessorOutputDecoder'
                options:
                    auto_setup: false
            awards:
                dsn: '%env(MESSENGER_TRANSPORT_AWARD_DSN)%'
                serializer: 'App\Messenger\Serializer\AwardEventDecoder'
                options:
                    auto_setup: false
            mailer:
                dsn: '%env(MESSENGER_TRANSPORT_MAILER_DSN)%'
        routing:
            App\Message\ProcessorOutputMessage: post-processing
            App\Message\Awards\NewEntryEventMessage: awards
            App\Message\Awards\NewPartEventMessage: awards
            Symfony\Component\Mailer\Messenger\SendEmailMessage: mailer

when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               post-processing: test://
               mailer: test://
