framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat/sns']
            high: ['chat/sns']
            medium: ['chat/sns']
            low: ['chat/sns']
        admin_recipients:
            - { email: admin@example.com }

when@test:
    framework:
        notifier:
            texter_transports:
