framework:
    notifier:
        chatter_transports:
        texter_transports:
            sns: '%env(NEW_ENTRY_SNS_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['fanout']
            high: ['fanout']
            medium: ['fanout']
            low: ['fanout']
        admin_recipients:
            - { email: admin@example.com }
