<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241207045533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create awards tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE awards (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(1024) NOT NULL, criteria JSON NOT NULL, type VARCHAR(255) NOT NULL, priority SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE awards_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, progress SMALLINT NOT NULL, award_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2093A1933D5282CF ON awards_progress (award_id)');
        $this->addSql('CREATE INDEX IDX_2093A193A76ED395 ON awards_progress (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_award_user ON awards_progress (award_id, user_id)');
        $this->addSql('CREATE TABLE awards_granted (id UUID NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, award_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_11EDCFFCA76ED395 ON awards_granted (user_id)');
        $this->addSql('CREATE INDEX IDX_11EDCFFC3D5282CF ON awards_granted (award_id)');
        $this->addSql('ALTER TABLE awards_progress ADD CONSTRAINT FK_2093A1933D5282CF FOREIGN KEY (award_id) REFERENCES awards (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE awards_progress ADD CONSTRAINT FK_2093A193A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE awards_granted ADD CONSTRAINT FK_11EDCFFCA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE awards_granted ADD CONSTRAINT FK_11EDCFFC3D5282CF FOREIGN KEY (award_id) REFERENCES awards (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE awards_progress DROP CONSTRAINT FK_2093A1933D5282CF');
        $this->addSql('ALTER TABLE awards_progress DROP CONSTRAINT FK_2093A193A76ED395');
        $this->addSql('ALTER TABLE awards_granted DROP CONSTRAINT FK_11EDCFFCA76ED395');
        $this->addSql('ALTER TABLE awards_granted DROP CONSTRAINT FK_11EDCFFC3D5282CF');
        $this->addSql('DROP TABLE awards');
        $this->addSql('DROP TABLE awards_progress');
        $this->addSql('DROP TABLE awards_granted');
    }
}
