<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241124191030 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29C18CC5C74F2195 ON user_jwt_refresh_tokens (refresh_token)');
        $this->addSql('ALTER TABLE entries ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE entries ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE entries ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE entries ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('COMMENT ON COLUMN entries.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN entries.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN entries.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN entries.updated_at IS \'\'');
        $this->addSql('ALTER TABLE entries_metadata ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE entries_metadata ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE entries_metadata ALTER entry_id TYPE UUID');
        $this->addSql('ALTER TABLE entries_metadata ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('COMMENT ON COLUMN entries_metadata.entry_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN entries_metadata.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_2153d45cba364942 RENAME TO IDX_275E8461BA364942');
        $this->addSql('ALTER TABLE users ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN users.id IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE user_refresh_token');
        $this->addSql('ALTER TABLE users ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE entries ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE entries ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE entries ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE entries ALTER user_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN entries.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN entries.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN entries.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN entries.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE entries_metadata ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE entries_metadata ALTER id SET DEFAULT entries_metadata_id_seq');
        $this->addSql('ALTER TABLE entries_metadata ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE entries_metadata ALTER entry_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN entries_metadata.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN entries_metadata.entry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE INDEX idx_entry_metatada_keywords_key ON entries_metadata (metadata) WHERE ((processor)::text = \'keywords\'::text)');
        $this->addSql('CREATE INDEX idx_entry_metatada_metadata_generic ON entries_metadata (metadata)');
        $this->addSql('ALTER INDEX idx_275e8461ba364942 RENAME TO idx_2153d45cba364942');
    }
}
