<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241201005706 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Base migration with entries, entries_metadata, parts, user_refresh_tokens and users tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entries (id UUID NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, part_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2DF8B3C5A76ED395 ON entries (user_id)');
        $this->addSql('CREATE INDEX IDX_2DF8B3C54CE34BEC ON entries (part_id)');
        $this->addSql('CREATE INDEX idx_entry_created_at ON entries (created_at)');
        $this->addSql('CREATE INDEX idx_entry_content_fulltext ON entries (content)');
        $this->addSql('CREATE TABLE entries_metadata (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, metadata JSONB NOT NULL, processor VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entry_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_275E8461BA364942 ON entries_metadata (entry_id)');
        $this->addSql('CREATE INDEX idx_entry_metatada_processor ON entries_metadata (processor)');
        $this->addSql('CREATE INDEX idx_entry_metatada_created_at ON entries_metadata (created_at)');
        $this->addSql('CREATE UNIQUE INDEX unique_entry_processor ON entries_metadata (entry_id, processor)');
        $this->addSql('CREATE TABLE parts (id UUID NOT NULL, name VARCHAR(100) NOT NULL, colors JSONB DEFAULT \'[]\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6940A7FEA76ED395 ON parts (user_id)');
        $this->addSql('CREATE TABLE user_refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F02938B8C74F2195 ON user_refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(320) NOT NULL, password VARCHAR(255) NOT NULL, google VARCHAR(255) DEFAULT NULL, apple VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE entries ADD CONSTRAINT FK_2DF8B3C5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entries ADD CONSTRAINT FK_2DF8B3C54CE34BEC FOREIGN KEY (part_id) REFERENCES parts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entries_metadata ADD CONSTRAINT FK_275E8461BA364942 FOREIGN KEY (entry_id) REFERENCES entries (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts ADD CONSTRAINT FK_6940A7FEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE entries DROP CONSTRAINT FK_2DF8B3C5A76ED395');
        $this->addSql('ALTER TABLE entries DROP CONSTRAINT FK_2DF8B3C54CE34BEC');
        $this->addSql('ALTER TABLE entries_metadata DROP CONSTRAINT FK_275E8461BA364942');
        $this->addSql('ALTER TABLE parts DROP CONSTRAINT FK_6940A7FEA76ED395');
        $this->addSql('DROP TABLE entries');
        $this->addSql('DROP TABLE entries_metadata');
        $this->addSql('DROP TABLE parts');
        $this->addSql('DROP TABLE user_refresh_tokens');
        $this->addSql('DROP TABLE users');
    }
}
