# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Symfony\Component\Notifier\Message\MessageOptionsInterface $entryProcessorSnsOptions: '@notifier.options.new_entry_processing_topic'
            Symfony\Component\Notifier\Message\MessageOptionsInterface $awardEventsSnsOptions: '@notifier.options.award_events_topic'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\EntityUserProvider
        arguments:
            $class: App\Entity\User
            $properties:
                'google': 'google'
                'apple': 'apple'

    texter:
        class: Symfony\Component\Notifier\Texter
        arguments:
            - '@texter.transports'
            - null
            - '@event_dispatcher'

    notifier.options.new_entry_processing_topic:
        class: Symfony\Component\Notifier\Bridge\AmazonSns\AmazonSnsOptions
        arguments: ['%env(NEW_ENTRY_PROCESSING_SNS_ARN)%']

    notifier.options.award_events_topic:
        class: Symfony\Component\Notifier\Bridge\AmazonSns\AmazonSnsOptions
        arguments: ['%env(AWARD_EVENTS_SNS_ARN)%']
